server:
  port: 10088

spring:
  application:
    name: tcp-server

# tcp
netty:
  server:
    host: 127.0.0.1
    port: 10086
    # 传输模式linux上开启会有更高的性能
    use-epoll: false

# 日记配置
logging:
  level:
    # 开启debug日记打印
    com.netty: debug